      CHARACTER CATBEN*64
      CHARACTER CATBU*24
      COMMON /BCMATBC/ CATBEN(JTAB),CATBU(JTAB)
C
C             CATBEN      - AUGMENTED TABLE B ELEMENT NAME
C             CATBU       - AUGMENTED TABLE B UNITS
C
C
