      INTEGER NJA,NATBTR,NATBS,
     1        NATBRV,NATBDW
      COMMON /BCMATB/ NJA,NATBTR(JTAB),NATBS(JTAB),
     1                NATBRV(JTAB),NATBDW(JTAB)
C
C
C             NATBTR      - AUGMENTED TABLE B TABLE REFERENCE
C             NATBS       - AUGMENTED TABLE B SCALE
C             NATBRV      - AUGMENTED TABLE B REFERENCE VALUE
C             NATBDW      - AUGMENTED TABLE B DATA WIDTH
C
C
