      CHARACTER*4      CECMWF,CUSER
      COMMON /BCMDEFC/ CECMWF,CUSER
C
C             CECMWF        -  CHARACTER STRING TO CONTROL DEFAULT SET UP
C             CUSER         -  CHARACTER STRING TO CONTROL USER SET UP
C
C
