      INTEGER        NTDLEN,NTDLST,       NTDEXL,NTDEXP
      COMMON /BCMEL/ NTDLEN,NTDLST(JELEM),NTDEXL,NTDEXP(JELEM)
C
C             NTDLEN - NUMBER OF DATA DESCRIPTORS IN SECTION 3
C             NTDLST - LIST OF DATA DESCRIPTORS
C             NTDEXL - NUMBER OF EXPANDED DATA DESCRIPTORS
C             NTDEXP - LIST OF EXPANDED DATA DESCRIPTORS
C
C
