      INTEGER        NWORDP,       NBITP
      COMMON /BCMRQ1/ NWORDP(JWORK)
      COMMON /BCMRQ2/ NBITP(JWORK)
C
C           NWORDP     - ARRAY CONTAINING WORD POINTERS TO
C                        REQUESTED ELEMENTS
C           NBITP      - ARRAY CONTAINING BIT POINTERS TO
C                        REQUESTED ELEMENTS
C
C
