      INTEGER         INWTEN,INWTR,INWTS,
     1                INWTRV,INWTDW,
     2                INWORDP,INBITP
      COMMON /BCOMP0/ INWTEN(JELEM),INWTR(JELEM),INWTS(JELEM),
     1                INWTRV (JELEM),INWTDW(JELEM)
      COMMON /BCOMP1/ INWORDP(JWORK)
      COMMON /BCOMP2/ INBITP(JWORK)
C
C             INWTEN    -  WORKING TABLE
C             INWTR     -  WORKING TABLE REFERENCE
C             INWTS     -  WORKING SCALE
C             INWTRV    -  WORKING REFERENCE VALUE
C             INWTDW    -  WORKING DATA WIDTH
C
