      CHARACTER CATBEN*64,CATBU*24
      COMMON /BCOMATBC/ CATBEN(JTAB),CATBU(JTAB)
C
C             CATBEN      - AUGMENTED TABLE B ELEMENT NAME
C             CATBU       - AUGMENTED TABLE B UNITS
C
C
