      INTEGER NWORDP,NBITP
      COMMON /BCOMRQ1/ NWORDP(JWORK)
      COMMON /BCOMRQ2/ NBITP(JWORK)
C
C           NWORDP     - ARRAY CONTAINING WORD POINTERS TO
C                        REQUESTED ELEMENTS
C           NBITP      - ARRAY CONTAINING BIT POINTERS TO
C                        REQUESTED ELEMENTS
C
C
