      INTEGER(KIND=JPIM),PARAMETER :: JSUP= 9
      INTEGER(KIND=JPIM),PARAMETER :: JSEC0 =3
      INTEGER(KIND=JPIM),PARAMETER :: JSEC1 =40
      INTEGER(KIND=JPIM),PARAMETER :: JSEC2 =64
      INTEGER(KIND=JPIM),PARAMETER :: JSEC3 =4
      INTEGER(KIND=JPIM),PARAMETER :: JSEC4 =2
      INTEGER(KIND=JPIM),PARAMETER :: JELEM =160000
      INTEGER(KIND=JPIM),PARAMETER :: JKEY  =46
      INTEGER(KIND=JPIM),PARAMETER :: JSUBS =400
      INTEGER(KIND=JPIM),PARAMETER :: JCVAL =150
      INTEGER(KIND=JPIM),PARAMETER :: JBUFL =512000
#ifdef JBPW_64
      INTEGER(KIND=JPIM),PARAMETER :: JBPW  =64
#else
      INTEGER(KIND=JPIM),PARAMETER :: JBPW  =32
#endif
      INTEGER(KIND=JPIM),PARAMETER :: JTAB  =3000
      INTEGER(KIND=JPIM),PARAMETER :: JCTAB =120
      INTEGER(KIND=JPIM),PARAMETER :: JCTST =1800
      INTEGER(KIND=JPIM),PARAMETER :: JCTEXT=200
      INTEGER(KIND=JPIM),PARAMETER :: JWORK =4096000
