!234567890c234567890c234567890c234567890c234567890c234567890c234567890--
NAMELIST /NAM_STDIN/&
    &NULOUT, NIN5, NOUT6, RUN_TYPE, VERIFY_RUN, DUPLICATE_CHECK,&
    &TIMERANGE_CHECK, CLUSTER_CHECK, TIMECLUSTER_CHECK,   &
    &INCREMENTAL_RUN, CANARI_RUN, USE_NEWCMAIO, USE_NEWBUFRIO,       &
    &SYNC_WRITE, SYNC_READ, OBSMAP_WRITE, OBSMAP_READ,&
    &SHUFFLE_CMA, SHUFFLE_BUFR, NPROCA, NPROCB, &
    &VNPROCA, VNPROCB, MAX_MSGLEN, MAX_MSGLAG, NTREE,               &
    &LBARRIER, LMERGE, OUT_OF_CORE_ECMA, MAX_IOBUFLEN,        &
    &LOG_FILE, NMLFILE, NUM_INPUT_FILES, CMA_INPUT, BUFR_INPUT,          &
    &NUM_OUTPUT_FILES, CMA_OUTPUT, BUFR_OUTPUT, NUM_TIME_SLOTS,      &
    &TIME_INIT_YYYYMMDD, TIME_INIT_HHMMSS, TIME_DELTA_4DVAR,    &
    &CLUSTER_TOL, PRINT_NFIRST_OBS, BACKWARD_TIME, FORWARD_TIME,&
    &OBSMAP_INPUT, OBSMAP_OUTPUT, FORCED_VIRTUAL,&
    &WRITE_ZERO_BUFR
